### ISSUE TITLE
yarn serve无法运行

### ISSUE THREAD

**Issue by whuiscool** [vue-alain/vue-alain#1]
git clone，yarn install后运行yarn serve，提示：
This dependency was not found:
* @/locales/zh_CN in ./src/main.ts
To install it, you can run: npm install --save @/locales/zh_CN

按照上面的提示又无法安装这个zh_CN

**Comment by whuiscool** [comment]
找到原因了，main.ts里的引用写错了，应该是：
import zh_CN from '@/locales/zh_cn';
cn要小写！

**Comment by ZhaoRd** [comment]
@whuiscool   我把文件改成大写了！这个是git 重命名引起的。感谢您提交的bug反馈
